name: smart_buy
description: "TaskFlow - Aplikacja do zarzÄ…dzania zadaniami i nawykami"
publish_to: 'none'

version: 2.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: any
  image_picker: ^1.0.7
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
