name: smart_buy
description: "TaskFlow - Aplikacja do zarzÄ…dzania zadaniami i nawykami"
publish_to: 'none'

version: 2.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: any
  image_picker: ^1.0.7
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/play_store_512.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/play_store_512.png"
